### ISSUE TITLE
frontend

### ISSUE THREAD

**Issue by abolore1** [Geerocktricks/NodeAssignment#1]
I need your front-end folder to validate you.

**Comment by Geerocktricks** [comment]
Should I re-submit?

**Comment by Geerocktricks** [comment]
Should I re-submit?

**Comment by abolore1** [comment]
I will advise u resubmit because others will surely face the same problem to assess you

**Comment by abolore1** [comment]
I will advice you resubmit because others will face similar problem from assessing you
